name: Containers Tool Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: '0 2 * * 0' # Weekly on Sundays at 02:00

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Containers tools image
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: buildah unshare ./build.sh
