name: Containers Tool Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: print user id
      run: id
    - name: print current directory
      run: pwd
    - name: Build the Containers tools image
      run: buildah unshare ./build.sh
    - name: list container images
      run: podman images
